quarkus:
    profile: dev

"%dev":
    quarkus:
        http:
            port: 8081
        oidc:
            auth-server-url: https://localhost:8543/auth/realms/quarkus
            client-id: backend-service
            credentials:
                secret: phHhahUQ5uASTOYoH9ehUoTmHT6jXFyq
            tls:
                verification: none
        datasource:
            db-kind: postgresql
            username: celk
            password: celk
            jdbc:
                url: jdbc:postgresql://localhost:5432/teste_quarkus
        hibernate-orm:
            database:
                generation: none
        smallrye-openapi:
            path: /swagger

#keycloak:
#    realm: quarkus
#    resource: client
#    auth-server-url: http://localhost:8543/auth/
#    credentials:
#        secret: '840c8b4a-6553-4c6c-968c-11543ff290c4'
#    bearer-only: true
#    use-resource-role-mappings: true
#    ssl-required: external

"%prod":
    quarkus:
        oidc:
            auth-server-url: https://localhost:8543/realms/quarkus
