services:
    keycloak_api:
        container_name: keycloak_api
        image: jboss/keycloak:latest
        restart: always
        depends_on:
            - keycloak_postgres_db
        ports:
            - "8543:8443"
        command:
            - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/quarkus-realm.json"
        volumes:
            - ./imports:/opt/jboss/keycloak/imports
        environment:
            KC_DB: postgres
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: kcpassword
            KC_DB_SCHEMA: public
            # KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak?ssl=allow
            KC_DB_URL_DATABASE: keycloak_postgres_db
            KC_DB_URL_HOST: keycloak_postgres_db
            KC_DB_URL_PORT: 5532
            # KC_DB_URL_PROPERTIES="verifyServerCertificate=false&ssl=allow"
            KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
            KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
            KC_HTTP_PORT: 8543
            KC_HTTP_ENABLED: "true"
            KC_HTTPS_PORT: 8543
            KC_HTTPS_PROTOCOLS: TLSv1.3,TLSv1.2
            KC_METRICS_ENABLED: "true"
            KC_PROXY: edge
            PROXY_ADDRESS_FORWARDING: "true"
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin

    keycloak_postgres_db:
        container_name: keycloak_postgres_db
        image: postgres
        restart: always
        ports:
            - '5532:5532'
        volumes:
            - postgres_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak_postgres_db
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: kcpassword
            PGDATA: /var/lib/postgresql/data/pgdata

volumes:
    postgres_db_data: